### ISSUE TITLE
ALFF/fALFF

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#15]
1) The alff.py function should calculate both ALFF and fractional ALFF (fALFF) images. At the moment only one is outputted. Is this fALFF?

2) Also, which image is currently the input for ALFF? This should be the data after ICA-AROMA, which has not been temporally filtered yet, as this will also be done in alff.py.

**Comment by ilyaveer** [comment]
Calculate stat images with FSL:

fslmaths <input img> -sub `fslstats <input img> -M` -div `fslstats <input img> -S` <output stat img>

**Comment by marcbue** [comment]
input imgs are reho_img.nii.gz, alff_img.nii.gz, falff_img.nii.gz
output imgs should be reho_zstat.nii.gz, alff_zstat.nii.gz, falff_zstat.nii.gz

**done**

**Comment by marcbue** [comment]
For 1.:
put ../subject/task_rest/alff_wf/_hp0.009/_lp0.08/stdev_fltrd/residual_3dT.nii.gz to intermediates/alff_img.nii.gz
put ../subject/task_rest/alff_wf/_hp0.009/_lp0.08/falff/ref_image_corrected.... to
intermediates/falff_img.nii.gz

**done**

**Comment by marcbue** [comment]
For 2:
input for alff/fallf workflow should be ../subject/task_rest/temporalfilter/highpass/denoised_func...
instead of preproc.nii.gz

**Change!**
input should be /subject/task_rest/func_preproc_01_rest/ica_aroma_wf/ica_aroma/out/denoised_func_data_nonaggr_tempfilt.nii.gz

**done**

**Comment by marcbue** [comment]
for higherlevel workflow under stats.py (**also for reho**):
    if outname in ["reho", "alff"]:
        flameo = pe.MapNode(
            interface=fsl.FLAMEO(
                run_mode=run_mode
            ),
            name="flameo",
            iterfield=["cope_file"]
        )

this currently uses the img_file in the future this should be the zstat file

**Comment by marcbue** [comment]
reho/alff/falff zstat created,
saved residual_3dT to intermediates as alff_img.nii.gz
saved ref_image_corrected... to intermediates as falff_img.nii.gz
input for alff/falff wf is now ../subject/task_rest/temporalfilter/highpass/denoised_func...

still open:
flameo of alff/reho in higherlevel should get zstat file instead of cope file, this is problematic because of the copes being merged, still needs some discussion

changes can be tested on dev as soon as docker is updated

**Comment by marcbue** [comment]
can be tested on dev
