### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by ebohorqu** [mindandbrain/pipeline#30]
Set a version for dev and master. Also indicate if code is for production or for developing.
Options for versioning: Increasing numbering, or release dates.

**Comment by marcbue** [comment]
I changed the version number for the master and dev branch according to the semanting versioning described here:
https://dzone.com/articles/how-to-version-your-software
So we still have 3 numbers and add master or dev at the end.
Bugfixes increase the third number.
New features increase the second number.
Major changes increase the first number.

We don't need to introduce internal versioning, since we use git and can use the hashcodes for each commit.

We just have to remember to update the info.py file accordingly everytime we push/merge something into dev/master.
