### ISSUE TITLE
check if individual files have been created in reports dir

### ISSUE THREAD

**Issue by ilyaveer** [mindandbrain/pipeline#36]
Currently, a reports dir is created. Most output files are correctly found, except for ones generated by the ICA template regression. In my data it now seems to look for files starting with ICA_templates_*, whereas in the intermediates these files are just called ICA_*.

As is indicated in report_summary.txt, individual reports are not found (e.g., report_lea_01_pipeline.txt). Should these be created, and where?

**Comment by ebohorqu** [comment]
@ilyaveer   Could you help me figuring out these things? 
* Were you using branch dev?
* Could you send me the files that were generated in reports/? also the json file you used, and any files in json_files/. I would need to know also the names of the intermediate files generated due to ICA.

Checking the code of branch dev, there is no hardcoded name to look for the files that need to be generated. The names are constructed based on the file names given in the setup and saved in the pipeline.json:
https://github.com/mindandbrain/pipeline/blob/765db7faa951cee06d7cbfa56aaf3fdbb7c81eed/pipeline/file_checks.py#L80

Also, if a block/individual json file is present in json_files/, then the respective report is looked for in reports/. When the respective file is not found, it is reported as such. They are generated after the execution of the respective json file. 
* If there are block/individual json files present in json_files/, but the whole pipeline was executed with pipeline.json instead, then the message could be ignored. 

https://github.com/mindandbrain/pipeline/blob/765db7faa951cee06d7cbfa56aaf3fdbb7c81eed/pipeline/file_checks.py#L177
